import React, { useEffect } from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
  Font,
} from "@react-pdf/renderer";
import logo from "../../../../assets/images/cokins-logo.png";

// Import Roboto Font
import RobotoRegular from "../../../../assets/fonts/Roboto-Regular.ttf";
import RobotoBold from "../../../../assets/fonts/Roboto-Bold.ttf";

Font.register({
  family: "Roboto",
  fonts: [{ src: RobotoRegular }, { src: RobotoBold, fontWeight: "bold" }],
});

const styles = StyleSheet.create({
  page: { padding: 20 },
  header: {
    marginBottom: 10,
    alignItems: "center",
  },
  logo: {
    width: 50,
    height: 50,
    marginBottom: 5,
  },
  companyName: {
    fontSize: 12,
    textAlign: "center",
    fontFamily: "Roboto",
    fontWeight: "bold",
  },
  reportTitle: {
    fontSize: 12,
    marginTop: 5,
    fontWeight: "bold",
    textAlign: "center",
    fontFamily: "Roboto",
  },
  sectionText: { fontSize: 10, textAlign: "center", marginTop: 5 },
  sectionText2: {
    fontSize: 10,
    textAlign: "left",
    marginTop: 5,
    fontFamily: "Roboto",
  },
  boldText: {
    fontWeight: "bold",
  },
  table: {
    display: "flex",
    width: "100%",
    border: "1px solid black",
    marginTop: 10,
  },
  tableRow: {
    flexDirection: "row",
    borderBottom: "1px solid black",
    width: "100%",
    display: "flex",
  },
  tableCol: {
    padding: 3,
    fontSize: 8,
    textAlign: "start",
    wordWrap: "break-word",
    borderRight: "1px solid black",
  },
  tableColLast: {
    padding: 3,
    fontSize: 8,
    textAlign: "start",
    wordWrap: "break-word",
  },
  tableColHeader: {
    padding: 3,
    fontSize: 8,
    fontWeight: "bold",
    textAlign: "center",
    color: "#fff",
    backgroundColor: "#4e73df",
    borderRight: "1px solid black",
  },
  // Column width styles
  colCompanyName: {
    width: "20%",
  },
  colContactPerson: {
    width: "15%",
  },
  colEmail: {
    width: "20%",
  },
  colPhone: {
    width: "12%",
  },
  colCity: {
    width: "11%",
  },
  colProvince: {
    width: "11%",
  },
  colCountry: {
    width: "11%",
  },
  footer: {
    marginTop: 20,
    fontSize: 10,
    textAlign: "center",
  },
  footerDetails: {
    fontSize: 9,
    marginTop: 5,
    textAlign: "center",
  },
});

const formatDate = (date) => {
  const options = { day: "numeric", month: "long", year: "numeric" };
  return new Date(date).toLocaleDateString("en-US", options);
};

const SupplierPDF = ({ data }) => {
  const userDetails = JSON.parse(localStorage.getItem('user')) || {};
  const generatedBy = userDetails ? `${userDetails.firstName || ''} ${userDetails.lastName || ''}` : 'Unknown User';

  useEffect(() => {}, []);

  return (
    <Document>
      <Page style={styles.page} size="A4" orientation="landscape">
        <View style={styles.header}>
          <Image style={styles.logo} src={logo} />
          <Text style={styles.companyName}>CEGM INVENTORY SYSTEMS</Text>
          <Text style={[styles.sectionText]}>
            109 Kayang St, Baguio, 2600 Benguet
          </Text>
          <Text style={[styles.sectionText]}>cokinsgenmdse0603@gmail.com</Text>
        </View>
        <View
          style={{
            borderBottomWidth: 0.5,
            borderBottomColor: "#000",
            marginVertical: 5,
          }}
        />
        <View style={styles.left}>
          <Text style={[styles.reportTitle, { fontWeight: "bold" }]}>
            SUPPLIER REPORT
          </Text>
          <Text style={styles.sectionText2}>
            <Text style={{ fontWeight: "bold" }}>No. of Suppliers: </Text>
            {data.length}
          </Text>
          <Text style={styles.sectionText2}>
            <Text style={{ fontWeight: "bold" }}>Document Name: </Text>
            Supplier Report
          </Text>
          <Text style={styles.sectionText2}>
            <Text style={{ fontWeight: "bold" }}>Report generated by: </Text>
            {generatedBy}
          </Text>
        </View>

        <View style={styles.table}>
          <View style={styles.tableRow}>
            <Text style={[styles.tableColHeader, styles.colCompanyName]}>Company Name</Text>
            <Text style={[styles.tableColHeader, styles.colContactPerson]}>Contact Person</Text>
            <Text style={[styles.tableColHeader, styles.colEmail]}>Email</Text>
            <Text style={[styles.tableColHeader, styles.colPhone]}>Phone</Text>
            <Text style={[styles.tableColHeader, styles.colCity]}>City</Text>
            <Text style={[styles.tableColHeader, styles.colProvince]}>Province</Text>
            <Text style={[styles.tableColHeader, styles.colCountry]}>Country</Text>
          </View>

          {data.map((supplier, index) => (
            <View
              style={[
                styles.tableRow,
                {
                  backgroundColor: index % 2 === 0 ? "#f9f9f9" : "#fff",
                },
              ]}
              key={supplier._id}
            >
              <Text style={[styles.tableCol, styles.colCompanyName]} numberOfLines={2}>{supplier.company_name}</Text>
              <Text style={[styles.tableCol, styles.colContactPerson]} numberOfLines={2}>{supplier.person_name}</Text>
              <Text style={[styles.tableCol, styles.colEmail]} numberOfLines={2}>{supplier.company_email}</Text>
              <Text style={[styles.tableCol, styles.colPhone]} numberOfLines={2}>{supplier.person_number}</Text>
              <Text style={[styles.tableCol, styles.colCity]} numberOfLines={2}>{supplier.company_city}</Text>
              <Text style={[styles.tableCol, styles.colProvince]} numberOfLines={2}>{supplier.company_province}</Text>
              <Text style={[styles.tableColLast, styles.colCountry]} numberOfLines={2}>{supplier.company_country}</Text>
            </View>
          ))}
        </View>

        <View style={styles.footer}>
          <Text style={styles.sectionText}>
            Report Generated on {formatDate(new Date())}
          </Text>
          <Text style={styles.footerDetails}>
            Contact: support@cegminventory.com | Page 1 of 1
          </Text>
        </View>
      </Page>
    </Document>
  );
};

export default SupplierPDF; 